/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include <inttypes.h>
#include "cycfg_qspi_memslot.h"
#include "cy_serial_flash_qspi.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Memory Read/Write size */
#define PACKET_SIZE             (64u)

/* Used when an array of data is printed on the console */
#define NUM_BYTES_PER_LINE      (16u)

/* LED blink delay */
#define LED_TOGGLE_DELAY_MSEC   (1000u)

/* QSPI clock frequency */
#define QSPI_BUS_FREQUENCY_HZ   (50000000lu)

/* Flash data after erase */
#define FLASH_DATA_AFTER_ERASE  (0xFFu)

/* Offset address from the top of QSPI device region */
#define ADDRESS                 (smifMemConfigs[0]->deviceCfg->eraseSize)

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: checkStatus
 * Summary:
 *  Prints the message, indicates the non-zero status by turning the LED on, and asserts the non-zero status.
 * Parameters:
 *  message - message to print if status is non-zero.
 *  status - status for evaluation.
 * Return:
 *  none
 **********************************************************************************************************************
 */
void checkStatus(char *message, uint32_t status)
{
    if (0u != status)
    {
        printf("\r\n================================================================================\r\n");
        printf("\nFAIL: %s\r\n", message);
        printf("Error Code: 0x%08"PRIX32"\n", status);
        printf("\r\n================================================================================\r\n");

        /* On failure, turn the LED ON */
        cyhal_gpio_write(CYBSP_USER_LED, CYBSP_LED_STATE_ON);
        CY_ASSERT(false);
    }
}

/**********************************************************************************************************************
 * Function Name: printArray
 * Summary:
 *  Prints the content of the buffer to the UART console.
 * Parameters:
 *  message - message to print before array output
 *  buf - buffer to print on the console.
 *  size - size of the buffer.
 * Return:
 *  none
 **********************************************************************************************************************
 */
void printArray(char *message, uint8_t *buf, uint32_t size)
{
    printf("\r\n%s (%"PRIu32" bytes):\r\n", message, size);
    printf("-------------------------\r\n");

    for (uint32_t index = 0; index < size; index++)
    {
        printf("0x%02X ", buf[index]);

        if (0u == ((index + 1) % NUM_BYTES_PER_LINE))
        {
            printf("\r\n");
        }
    }
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Return:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
    cy_rslt_t   result;
    uint8_t     txBuf[PACKET_SIZE];
    uint8_t     rxBuf[PACKET_SIZE];
    size_t      size = PACKET_SIZE;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    CY_ASSERT(result == CY_RSLT_SUCCESS);

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");
    printf("*************** QSPI Flash Read and Write using serial-flash library ***************\r\n\n");

    /* Initialize the User LED */
    result = cyhal_gpio_init(CYBSP_USER_LED, CYHAL_GPIO_DIR_OUTPUT, CYHAL_GPIO_DRIVE_STRONG, CYBSP_LED_STATE_OFF);
    checkStatus("User LED initialization failed", result);

    /* initialize serial-flash library */
    result = cy_serial_flash_qspi_init(smifMemConfigs[0], CYBSP_QSPI_D0,
    CYBSP_QSPI_D1, CYBSP_QSPI_D2, CYBSP_QSPI_D3, NC, NC, NC, NC, CYBSP_QSPI_SCK,
    CYBSP_QSPI_SS, QSPI_BUS_FREQUENCY_HZ);
    checkStatus("Serial Flash initialization failed", result);

    /* sector erase */
    printf("\r\n1. Erasing \r\n");
    result = cy_serial_flash_qspi_erase(ADDRESS, smifMemConfigs[0]->deviceCfg->eraseSize);
    checkStatus("Erasing memory failed", result);

    /* Read after erased */
    printf("\r\n2. Reading after Erase and verifying that each byte is 0xFF\r\n");
    result = cy_serial_flash_qspi_read(ADDRESS, size, rxBuf);
    checkStatus("Reading from memory failed", result);
    printArray("Received Data", rxBuf, PACKET_SIZE);
    memset(txBuf, FLASH_DATA_AFTER_ERASE, PACKET_SIZE);
    checkStatus("Flash contains data other than 0xFF after erase", memcmp(txBuf, rxBuf, PACKET_SIZE));

    /* Prepare the TX buffer */
    for (uint32_t index = 0; index < PACKET_SIZE; index++)
    {
        txBuf[index] = (uint8_t)index;
    }

    /* Write the content of the TX buffer to the memory */
    printf("\r\n3. Writing data to memory\r\n");
    /* Write page */
    result = cy_serial_flash_qspi_write(ADDRESS, size, txBuf);
    checkStatus("Writing to memory failed", result);
    printArray("Written Data", txBuf, PACKET_SIZE);

    /* Read back after Write for verification */
    printf("\r\n4. Reading back for verification\r\n");

    /* Read page */
    result = cy_serial_flash_qspi_read(ADDRESS, size, rxBuf);
    checkStatus("Reading from memory failed", result);
    printArray("Received Data", rxBuf, PACKET_SIZE);
    checkStatus("Read data does not match with written data. Read/Write operation failed.",
                 memcmp(txBuf, rxBuf, PACKET_SIZE));

    printf("\r\n================================================================================\r\n");
    printf("\r\nSUCCESS: Read data matches with written data!\r\n");
    printf("\r\n================================================================================\r\n");

    for (;;)
    {
        cyhal_gpio_toggle(CYBSP_USER_LED);
        cyhal_system_delay_ms(LED_TOGGLE_DELAY_MSEC);
    }
}

/* [] END OF FILE */
